
logging:
  level: debug
spring:
  application:
    name: mq-consumer
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
        defaultZone: http://ellien:jiangkui1991@peer1:1111/eureka/
#        ,http://ellien:jiangkui1991@peer2:1112/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2      #心跳
    lease-expiration-duration-in-seconds: 6  #服务失效时间

management:
  security:
    enabled: false # 刷新时，关闭安全验证
server:
  port: 8088

