spring:
  application:
    name: server-register
eureka:
  server:
    enable-self-preservation: true # 关闭保护机制
security:
  basic:
    enabled: false
  user:
    name: ellien
    password: 123456


---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 1111
eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://ellien:123456@peer2:1112/eureka/     # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: peer2
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: false           #是否已自身为实例注册到eureka服务端
    fetch-registry: false
    serviceUrl:
      defaultZone: http://ellien:123456@peer1:1111/eureka/