logging:
  level: debug
spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
        defaultZone: http://ellien:jiangkui1991@peer1:1111/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2      #心跳
    lease-expiration-duration-in-seconds: 6
zuul:
  routes:
    user-route:
      path: /user/**
      service-id: user-service
  ignored-services: '*'

   #服务失效时间
    #instance-id: ${spring.application.name}:${random.int} #随机实例名
#server:
  #port: ${random.int[8090,8200]} #随机端口
