logging:
  level: debug
spring:
  application:
    name: common-service
  jpa:
    database: mysql
    show-sql: true
    hibernate:
          ddl-auto: none #使用自建表
  boot:
      admin:
        url: http://localhost:8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://ellien:jiangkui1991@peer1:1111/eureka/,http://ellien:jiangkui1991@peer2:1112/eureka
  instance:
    prefer-ip-address: true
hystrix:
  metrics:
    enabled: true
  config:
    stream:
       maxConcurrentConnections: 50
